version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          #pkg-manager: jest
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          echo "npm run test:jest"
          npm run test
          # jest
  
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      #- docker/check:
      - docker/check
          #docker-username: DOCKERHUB_LOGIN  # DOCKER_LOGIN is the default value, if it exists, it automatically would be used.
          #docker-password: DOCKERHUB_PASSWORD   # DOCKER_PASSWORD is the default value
      - docker/build:
          image: andyliu2025sg/node-app
      - docker/push:
          image: andyliu2025sg/node-app
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker      
      #- heroku/install
      - checkout
      - run:
          name: Authenticate with Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - run:  
          name: Build and Push Docker Image
          command: |  
              IMAGE_NAME=andyliu2025sg/node-app
              IMAGE_TAG=latest

              docker build -t $IMAGE_NAME:$IMAGE_TAG .
              docker push $IMAGE_NAME:$IMAGE_TAG



workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish